[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "mutagen>=1.47.0",
    "psycopg2-binary>=2.9.10",
    "sendgrid>=6.12.4",
    "streamlit>=1.49.1",
    "stripe>=12.5.1",
]
